title: Megan Steffes # your name (or website title) here
logo: "/images/MS.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GIS Specialist with 5+ years experience in ESRI products including ArcGIS Pro, ArcGIS Online, Survey123, and more!
  Some experience with various programming languages including Python, SQL, and R.
  <br><br>
  Currently pursuing a Masters of Science in Geospatial Technologies from the University of Oklahoma.
  <br><br>
  <a href="https://www.linkedin.com/in/megan-steffes">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
> # google_analytics: UA-000000-0 # your Google Analytics tracking ID here
